### PR TITLE
Adds `dired-atool-default-to-current-dir' to disable location prompt

### PR DESCRIPTION
**Pull request by xenodium**
Adds the ability to turn off asking users for the target location and always extract to current directory.

### CODE REVIEW

**Comment by HKey** [comment]
Hi, thank you for the PR.

Does this change intend to extract files directly without confirmation like `dired-do-compress` (`Z`) when `dired-no-confirm` contains `compress`?

I'm concerned about how to implement the feature because `dired-atool-do-unpack` intend to extract files to a specified location.
If disable the confirmation of `dired-atool-do-unpack`, I'm worried about whether it is intuitive that extracting files to current directory when `dired-dwim-target` is non-nil and there is another dired window.
Because `dired-atool-do-unpack` considers `dired-dwim-target`.
On the other hand, if disable confirmation, I think it would be better to disable confirmation of `dired-atool-do-unpack-with-subdirectory` too.

Ideally, I should have separated `dired-atool-do-unpack` to 2 commands like `dired-do-compress` and `dired-do-compress-to`.
If the command is separated, it will be intuitive that `dired-atool-do-unpack` and `dired-atool-do-unpack-with-subdirectory` extract files without confirmation by enabling an option.
Because only the new command (e.g. `dired-atool-do-unpack-to`) need the location to extract to.

If separating `dired-atool-do-unpack`, it will be a breaking change because the meaning of `dired-atool-do-unpack` is changed to "extract files to current directory".
To adopt this way, I think it will be need to announce the breaking change and set some period before the implementation changing.
I prefer this way if I could.
But if so, I want some time to plan how to announce and introduce the breaking change.

Please feel free to comment.

**Comment by xenodium** [comment]
Thanks for the detailed reponse @HKey 

> Does this change intend to extract files directly without confirmation like dired-do-compress (Z) when dired-no-confirm contains compress?

Similar, but it does not rely on `dired-no-confirm` but the new `dired-atool-default-to-current-dir` var to disable choosing a location in `dired-atool-do-unpack`.

> I'm concerned about how to implement the feature because dired-atool-do-unpack intend to extract files to a specified location.

Checking for `dired-atool-default-to-current-dir` in PR handles that?

https://github.com/HKey/dired-atool/pull/6/files#diff-132d60f01c3f231971092a5e07f16ddc8ba08f3e279684becafabf631586d576R129

```
+         (dir (if dired-atool-default-to-current-dir
+                  default-directory
+                (expand-file-name    ; to expand "~" to a real path name
+                 (dired-mark-pop-up
+                  nil nil files
+                  #'read-directory-name
+                  (format "Unpack %s to: "
+                          (dired-atool--file-names-for-prompt files))
+                  (dired-dwim-target-directory)))
+                default-directory))
```

> If disable the confirmation of dired-atool-do-unpack, I'm worried about whether it is intuitive that extracting files to current directory when dired-dwim-target is non-nil and there is another dired window.

`dired-atool-default-to-current-dir`'s default value is nil (keeping current behaviour unchanged). Users that would like to change that behavior would explicitly set `dired-atool-default-to-current-dir` to `t`, thus aware of the behavior change they explicitly requested?

> Ideally, I should have separated dired-atool-do-unpack to 2 commands like dired-do-compress and dired-do-compress-to.

Do you mean `unpack`, instead of `compress`? so `dired-atool-do-unpack` and `dired-atool-do-unpack-to`?

I can look at making a separate command if you prefer. It would require a little more refactoring to reuse common logic. At present, the change in PR is fairly unobtrusive. Lemme know if you'd prefer to go with small refactor.

> On the other hand, if disable confirmation, I think it would be better to disable confirmation of dired-atool-do-unpack-with-subdirectory too.

The goal of `dired-atool-default-to-current-dir` was more to disable asking the user for a target location than disabling y/n prompt. Having said that, happy to use `dired-atool-default-to-current-dir` in `dired-atool-do-unpack-with-subdirectory` if you'd like it to disable `yes-or-no-p` also.

> To adopt this way, I think it will be need to announce the breaking change and set some period before the implementation changing.

I rather not break existing users at all (Emacs is generally good at that). If we prefer separate commands, I would suggest we keep `dired-atool-do-unpack` and introduce something like `dired-atool-do-unpack-to-current-dir`. This change would not break any existing user nor require changes from them.

I think we currently have two options:

1. Evolve the current change https://github.com/HKey/dired-atool/pull/6/files#diff-132d60f01c3f231971092a5e07f16ddc8ba08f3e279684becafabf631586d576R129 to also use `dired-atool-default-to-current-dir` in `dired-atool-do-unpack-with-subdirectory`. This would be the smallest change. No breaking changes for existing users.

2. Refactor the code to reuse common logic and split into two commands: `dired-atool-do-unpack` and `dired-atool-do-unpack-to-current-dir`. This change a bit more involved, so it depends on your appetite for some refactoring. Also no breaking changes for existing users.

First option seems more straightforward. Lemme know which one you'd like to go with.

**Comment by HKey** [comment]
Thank you for the detailed reply.

> > I'm concerned about how to implement the feature because dired-atool-do-unpack intend to extract files to a specified location.
>
> Checking for dired-atool-default-to-current-dir in PR handles that?

> > If disable the confirmation of dired-atool-do-unpack, I'm worried about whether it is intuitive that extracting files to current directory when dired-dwim-target is non-nil and there is another dired window.
>
> dired-atool-default-to-current-dir's default value is nil (keeping current behaviour unchanged). Users that would like to change that behavior would explicitly set dired-atool-default-to-current-dir to t, thus aware of the behavior change they explicitly requested?

You're right.
I had been worried about users that they want to extract files into a directory of another dired window.
But that worry wasn't so important.

> > Ideally, I should have separated dired-atool-do-unpack to 2 commands like dired-do-compress and dired-do-compress-to.
>
> Do you mean unpack, instead of compress? so dired-atool-do-unpack and dired-atool-do-unpack-to?

Yes.

> I think we currently have two options:

I'd like to separate `dired-atool-do-unpack` into two commands `dired-atool-do-unpack` and `dired-atool-do-unpack-to-current-dir`.

The reasons are:

- To inherit dired's command design (separated into 2 commands) to reduce users' confusion.
- To make the effect of the option descriptive.
  Basically dired-atool's commands are designed to confirm before doing their actions.
  So, I think it is important to show disabling confirmation to users by option name.

To adopt this way, we need to do these things:

- Separate `dired-atool-do-unpack` into two commands `dired-atool-do-unpack` and `dired-atool-do-unpack-to-current-dir`.
  `dired-atool-do-unpack` remains as it is.
  `dired-atool-do-unpack-to-current-dir` is a new command affected by new option, it prompts yes/no before doing its action by default.
- Change the name of the new option.
  Because now the meaning has been changed to disable confirmation.
  And I think it is better that the name indicates that the option affects unpacking only, like `dired-atool-unpack-no-confirm`.
  Whether we add a similar option for packing may be another issue, so I'll consider it later.
- Change `dired-atool-do-unpack-with-subdirectory` to be affected by the new option.

I'm thinking about renaming `dired-atool-do-unpack-with-subdirectory` to keep consistency of command suffix, like `dired-atool-do-unpack-with-subdirectory-to-current-dir`.
But it is not necessary in this PR, I'll consider this later too.

Sorry for making this change more complex.
Could you update your changes?

Here's some advice from current changes review:

- Increase version to "1.3.0".
  dired-atool follows [Semantic Versioning 2.0.0](https://semver.org/).
  This change is adding a new feature, so we need to increase the minor version.
- Use `dired-current-directory` function instead of `default-directory` variable.
  This is to keep consistency with `dired-dwim-target-directory` about getting the current directory.
  `dired-dwim-target-directory` is used by `dired-atool-do-unpack`.

**Comment by xenodium** [comment]
> I'd like to separate dired-atool-do-unpack into two commands dired-atool-do-unpack and dired-atool-do-unpack-to-current-dir.

Sounds good.

> To adopt this way, we need to do these things:
> 
>     * Separate `dired-atool-do-unpack` into two commands `dired-atool-do-unpack` and `dired-atool-do-unpack-to-current-dir`.

Done

>       `dired-atool-do-unpack` remains as it is.

Done

>       `dired-atool-do-unpack-to-current-dir` is a new command affected by new option, it prompts yes/no before doing its action by default.

Done

>     * Change the name of the new option.

Done

> Sorry for making this change more complex.

No problem

> Here's some advice from current changes review:
> 
>     * Increase version to "1.3.0".

Done

>     * Use `dired-current-directory` function instead of `default-directory` variable.

Done

ps. Sorry. I amended my commit to simplify PR, but may not result in a clean merge. Happy to open a separate PR.

**Comment by HKey** [comment]
Thank you for the quick update.

I changed the merge commit message because the actual changes no longer match this PR's description. 

> ps. Sorry. I amended my commit to simplify PR, but may not result in a clean merge. Happy to open a separate PR.

No problem.

It's just a guess, simplifying commits and force pushing might have worked to clean the commit history.

**Comment by xenodium** [comment]
Thanks for reviewing and merging!

**Pull request merged**
